### PR TITLE
Fix signout redirect on staging

### PR DESCRIPTION
**Pull request by cooperka**
You'll just need to set `REACT_APP_APP_PATH=/blockpower` on staging. It should default to `/` like this for local development.

### CODE REVIEW

**Comment by shauminn-colab** [comment]
I just tested on stage2 and signout is still redirecting to https://stage2.app.blockpower.vote/ rather than https://stage2.app.blockpower.vote/blockpower

**Comment by cooperka** [comment]
Have you set `REACT_APP_APP_PATH=/blockpower` and restarted it?

**Comment by shauminn-colab** [comment]
We updated that env var to `REACT_APP_APP_PATH=/blockpower` and redeployed to stage2 but unfortunately the redirect doesn't seem to be working -- it's still hitting the / route and throwing a 403 .. should the env var definitely be set that way or is there something in the code that might need fixing?

**Comment by shauminn-colab** [comment]
Ah wait, we just noticed the issue: REACT_APP_APP_PATH should be REACT_APP_APPPATH so we are updating and might be all set. Testing again shortly :)

**Comment by cooperka** [comment]
`REACT_APP_APPPATH` is old and unused, it should definitely be `REACT_APP_APP_PATH` -- it works locally so I wonder if it's not picking up the change to .env properly? Could be worth printing the value of `REACT_APP_APP_PATH` to the console or webpage so you can see if it's actually recognized. Let me know if I can help.

**Comment by shauminn-colab** [comment]
hrm, Jure changed it to REACT_APP_APPPATH and it now works on stage2 ... argh sorry this is confusing

**Pull request merged**
