### PR TITLE
added DeniedPage component to warn ambassadors 'Account under review'

### PR DESCRIPTION
**Pull request by azrap**
Addressing Issue #155 

Added a DeniedPage component to hello-voter/src/components/Profile/ContactInfoPage.js which gets displayed when an ambassador's account is under review due to fraudulent activity. 

Screen Shot 2020-10-13 at 6 00 30 PM

### CODE REVIEW

**Comment by shauminn-colab** [comment]
@litenull - if this looks good to you, please merge!  It's expected that for now all items on nav bar redirect to this denied page except for Help page, which should be available to the user.

**Comment by litenull** [comment]
Hm, this should be global, not just on one page, right ?
EDIT: Ok, seems like only for menu items.

**Comment by shauminn-colab** [comment]
@azrap - just realized that on mobile Vote Triplers and Payments buttons are still visible. If you're able to fix this today (Saturday 10/17) let me know. Otherwise I can look for someone else who might be able to pick up
Screen Shot 2020-10-17 at 8 28 34 AM

**Comment by shauminn-colab** [comment]
PR going in for mobile menu fix 👍

**Pull request merged**
